services:
  postgres:
    image: postgres:16
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: tester
      POSTGRES_PASSWORD: randomtest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
